### PR TITLE
Fixed a bug on demo cart

### PR DESCRIPTION
**Pull request by AssisrMatheus**
The function names in the cart were not correctly cased. Causing the demo to break

### CODE REVIEW

**Comment by JoebRogers** [comment]
"Causing the demo to break" - Could you expand on this? The demo runs completely fine, as the PICO-8 is case insensitive. Unless there's been an update to the console since this was originally written, changing this?

**Comment by AssisrMatheus** [comment]
It didn't let me change to the other functions with the arrow keys and it just kept in the first one. Because you try to search the array by its index. Pico8 is not case sensitive but lua array indexing still is 
:(

**Comment by JoebRogers** [comment]
Hmm, interesting that you run into that issue, as it works fine for me and has done in the past on previous devices I've tested with too. I'll merge the request anyway for sake of compatability, but if you wouldn't mind letting me know what version of PICO-8 you're running, and platform? Thanks!

**Comment by AssisrMatheus** [comment]
image

This is the version I tested it with. On windows 10!

**Comment by AssisrMatheus** [comment]
SIZaKOqYrQ

This is what happens when I press the arrow keys. It just doesn't change to the next function and restarts the current one, making the ball do a strange "jump"

**Comment by JoebRogers** [comment]
Thanks for the info! I'll check through the version notes when I get a chance and see when the bug was introduced. The last tested working version was on 0.1.11G.

**Pull request merged**
